#!/usr/bin/python3

def raise_exception_msg(message=""):
    """Return NameError """
    raise NameError(message)
